# Generated by Django 3.0.8 on 2020-08-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=500)),
                ('content', models.TextField()),
            ],
        ),
    ]
